language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  # - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.2.1

matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: jruby-19mode
